/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal projects. It is committed here so
// the static frontend has a complete TypeScript scaffold before dependencies run.
