const seedTimestamp = new Date().toISOString();

const listingImages = [
  "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1560448075-bb485b067938?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1560448205-4d9b3e6bb6db?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80"
];

const roommateImages = [
  "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1527980965255-d3b416303d12?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?auto=format&fit=crop&w=900&q=80"
];

export const seedListings = [
  {
    id: "seed-listing-1",
    title: "Westwood UCLA 步行圈阳光主卧",
    area: "Los Angeles · Westwood",
    image: listingImages[0],
    price: 1680,
    originalPrice: 1950,
    beds: 1,
    baths: 1,
    commute: "步行 12 分钟到 UCLA",
    transit: "公交 18 分钟到 Sawtelle",
    trust: ".edu 已认证 · 房东知情",
    tags: ["独卫", "带家具", "可 8/20 入住"],
    score: 4.93,
    ownerId: "seed-user",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp
  },
  {
    id: "seed-listing-2",
    title: "Koreatown 地铁口 2B2B 合租",
    area: "Los Angeles · Koreatown",
    image: listingImages[1],
    price: 1320,
    originalPrice: 1580,
    beds: 2,
    baths: 2,
    commute: "紫线 16 分钟到 DTLA",
    transit: "步行 5 分钟到 Wilshire/Normandie",
    trust: "视频验房 · 合同存证",
    tags: ["近地铁", "洗烘", "Group 推荐"],
    score: 4.86,
    ownerId: "seed-user",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp
  },
  {
    id: "seed-listing-3",
    title: "Culver City 实习通勤 1B1B",
    area: "Los Angeles · Culver City",
    image: listingImages[2],
    price: 2140,
    originalPrice: 2450,
    beds: 1,
    baths: 1,
    commute: "轻轨 14 分钟到 Santa Monica",
    transit: "E Line 22 分钟到 USC",
    trust: "企业邮箱认证 · 首日保障",
    tags: ["车位", "健身房", "可短租"],
    score: 4.82,
    ownerId: "seed-user",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp
  },
  {
    id: "seed-listing-4",
    title: "Santa Monica 海边 Studio 转租",
    area: "Los Angeles · Santa Monica",
    image: listingImages[3],
    price: 2380,
    originalPrice: 2720,
    beds: 1,
    baths: 1,
    commute: "骑行 10 分钟到 Promenade",
    transit: "E Line 28 分钟到 Culver City",
    trust: "原租客高分 · 房东知情",
    tags: ["近海边", "采光好", "带家具"],
    score: 4.9,
    ownerId: "seed-user",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp
  },
  {
    id: "seed-listing-5",
    title: "Silver Lake 安静次卧短租",
    area: "Los Angeles · Silver Lake",
    image: listingImages[4],
    price: 1260,
    originalPrice: 1480,
    beds: 2,
    baths: 1,
    commute: "公交 20 分钟到 Hollywood",
    transit: "驾车 18 分钟到 Glendale",
    trust: "室友背调 · 视频验房",
    tags: ["无烟", "猫友好", "安静"],
    score: 4.77,
    ownerId: "seed-user",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp
  },
  {
    id: "seed-listing-6",
    title: "Pasadena Caltech 附近主卧",
    area: "Los Angeles · Pasadena",
    image: listingImages[5],
    price: 1490,
    originalPrice: 1710,
    beds: 1,
    baths: 1,
    commute: "骑行 9 分钟到 Caltech",
    transit: "A Line 25 分钟到 Chinatown",
    trust: ".edu 已认证 · 合同存证",
    tags: ["独卫", "车位", "学习友好"],
    score: 4.88,
    ownerId: "seed-user",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp
  },
  {
    id: "seed-listing-7",
    title: "Downtown LA 高层 Loft",
    area: "Los Angeles · DTLA",
    image: listingImages[6],
    price: 1960,
    originalPrice: 2260,
    beds: 1,
    baths: 1,
    commute: "步行 8 分钟到 Financial District",
    transit: "地铁 12 分钟到 USC Village",
    trust: "企业邮箱认证 · 门禁记录",
    tags: ["门卫", "健身房", "地铁口"],
    score: 4.79,
    ownerId: "seed-user",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp
  },
  {
    id: "seed-listing-8",
    title: "USC North 3B2B Group 优选",
    area: "Los Angeles · USC North",
    image: listingImages[7],
    price: 3620,
    originalPrice: 4100,
    beds: 3,
    baths: 2,
    commute: "步行 11 分钟到 USC",
    transit: "校车 8 分钟到 Viterbi",
    trust: "三方协议模板 · 房东知情",
    tags: ["整租", "Group 推荐", "可分租"],
    score: 4.91,
    ownerId: "seed-user",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp
  },
  {
    id: "seed-listing-9",
    title: "Hollywood Hills 景观 1B",
    area: "Los Angeles · Hollywood",
    image: listingImages[8],
    price: 2050,
    originalPrice: 2380,
    beds: 1,
    baths: 1,
    commute: "红线 15 分钟到 Universal City",
    transit: "驾车 22 分钟到 Burbank",
    trust: "视频验房 · 低纠纷记录",
    tags: ["景观", "可短租", "洗烘"],
    score: 4.73,
    ownerId: "seed-user",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp
  },
  {
    id: "seed-listing-10",
    title: "Burbank 影视实习友好次卧",
    area: "Los Angeles · Burbank",
    image: listingImages[9],
    price: 1180,
    originalPrice: 1390,
    beds: 2,
    baths: 1,
    commute: "公交 12 分钟到 Warner Bros",
    transit: "Metrolink 20 分钟到 Glendale",
    trust: "原租客推荐 · 房东知情",
    tags: ["影视实习", "安静", "车位"],
    score: 4.69,
    ownerId: "seed-user",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp
  },
  {
    id: "seed-listing-11",
    title: "Sawtelle 日系街区主卧",
    area: "Los Angeles · Sawtelle",
    image: listingImages[0],
    price: 1760,
    originalPrice: 2050,
    beds: 1,
    baths: 1,
    commute: "公交 13 分钟到 UCLA",
    transit: "驾车 12 分钟到 Santa Monica",
    trust: ".edu 已认证 · 视频验房",
    tags: ["独卫", "餐饮方便", "带家具"],
    score: 4.87,
    ownerId: "seed-user",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp
  },
  {
    id: "seed-listing-12",
    title: "Glendale 安全小区 2B1B",
    area: "Los Angeles · Glendale",
    image: listingImages[1],
    price: 2480,
    originalPrice: 2820,
    beds: 2,
    baths: 1,
    commute: "驾车 15 分钟到 Pasadena",
    transit: "公交 24 分钟到 Burbank",
    trust: "门禁小区 · 合同存证",
    tags: ["整租", "车位", "宠物友好"],
    score: 4.74,
    ownerId: "seed-user",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp
  },
  {
    id: "seed-listing-13",
    title: "Mar Vista 采光 Studio",
    area: "Los Angeles · Mar Vista",
    image: listingImages[2],
    price: 1880,
    originalPrice: 2140,
    beds: 1,
    baths: 1,
    commute: "骑行 16 分钟到 Venice",
    transit: "公交 18 分钟到 Culver City",
    trust: "金牌转租人 · 首日保障",
    tags: ["采光好", "可做饭", "近公交"],
    score: 4.81,
    ownerId: "seed-user",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp
  },
  {
    id: "seed-listing-14",
    title: "Echo Park 湖边合租房",
    area: "Los Angeles · Echo Park",
    image: listingImages[3],
    price: 1210,
    originalPrice: 1450,
    beds: 3,
    baths: 2,
    commute: "公交 18 分钟到 DTLA",
    transit: "驾车 14 分钟到 Silver Lake",
    trust: "室友认证 · 房东知情",
    tags: ["合租", "宠物友好", "预算友好"],
    score: 4.72,
    ownerId: "seed-user",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp
  },
  {
    id: "seed-listing-15",
    title: "Playa Vista 科技园 1B1B",
    area: "Los Angeles · Playa Vista",
    image: listingImages[4],
    price: 2290,
    originalPrice: 2650,
    beds: 1,
    baths: 1,
    commute: "步行 14 分钟到 Silicon Beach",
    transit: "公交 23 分钟到 LMU",
    trust: "企业邮箱认证 · 物业确认",
    tags: ["健身房", "泳池", "车位"],
    score: 4.85,
    ownerId: "seed-user",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp
  },
  {
    id: "seed-listing-16",
    title: "North Hollywood 地铁旁 2B",
    area: "Los Angeles · North Hollywood",
    image: listingImages[5],
    price: 1710,
    originalPrice: 1980,
    beds: 2,
    baths: 2,
    commute: "红线 10 分钟到 Universal City",
    transit: "地铁 25 分钟到 Hollywood",
    trust: "视频验房 · 合同模板",
    tags: ["近地铁", "整租", "洗烘"],
    score: 4.7,
    ownerId: "seed-user",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp
  },
  {
    id: "seed-listing-17",
    title: "Los Feliz 复古公寓主卧",
    area: "Los Angeles · Los Feliz",
    image: listingImages[6],
    price: 1540,
    originalPrice: 1790,
    beds: 2,
    baths: 1,
    commute: "步行 9 分钟到 Vermont/Sunset",
    transit: "红线 14 分钟到 Hollywood",
    trust: "原租客高分 · 房东知情",
    tags: ["复古公寓", "安静", "近地铁"],
    score: 4.78,
    ownerId: "seed-user",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp
  },
  {
    id: "seed-listing-18",
    title: "Brentwood 明亮 1B 转租",
    area: "Los Angeles · Brentwood",
    image: listingImages[7],
    price: 2180,
    originalPrice: 2490,
    beds: 1,
    baths: 1,
    commute: "公交 16 分钟到 UCLA",
    transit: "驾车 13 分钟到 Santa Monica",
    trust: ".edu 已认证 · 低纠纷记录",
    tags: ["带家具", "采光好", "安静"],
    score: 4.84,
    ownerId: "seed-user",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp
  },
  {
    id: "seed-listing-19",
    title: "Arts District 工业风 Loft",
    area: "Los Angeles · Arts District",
    image: listingImages[8],
    price: 2210,
    originalPrice: 2550,
    beds: 1,
    baths: 1,
    commute: "步行 12 分钟到 Little Tokyo",
    transit: "A/E Line 16 分钟到 DTLA",
    trust: "物业确认 · 视频验房",
    tags: ["Loft", "门卫", "可短租"],
    score: 4.76,
    ownerId: "seed-user",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp
  },
  {
    id: "seed-listing-20",
    title: "El Segundo 海边通勤 2B2B",
    area: "Los Angeles · El Segundo",
    image: listingImages[9],
    price: 2860,
    originalPrice: 3260,
    beds: 2,
    baths: 2,
    commute: "驾车 10 分钟到 LAX",
    transit: "公交 20 分钟到 Manhattan Beach",
    trust: "企业邮箱认证 · 房东知情",
    tags: ["海边通勤", "整租", "车位"],
    score: 4.8,
    ownerId: "seed-user",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp
  }
].map((listing) => ({
  ...listing,
  availableFrom: "2026-08-01",
  availableTo: "2027-08-01"
}));

export const seedRoommates = [
  {
    id: "seed-roommate-1",
    name: "Mia Chen",
    age: 22,
    role: "UCLA MSBA · 秋季入学",
    image: roommateImages[0],
    match: 96,
    budget: "$1,650/月",
    commute: "Westwood / Sawtelle",
    tags: ["早睡", "少做饭", "无宠物", "安静"]
  },
  {
    id: "seed-roommate-2",
    name: "Ethan Liu",
    age: 24,
    role: "Culver City Product Intern",
    image: roommateImages[1],
    match: 91,
    budget: "$1,850/月",
    commute: "Culver City / Santa Monica",
    tags: ["可合租", "周末社交", "爱干净", "健身"]
  },
  {
    id: "seed-roommate-3",
    name: "Ava Zhang",
    age: 23,
    role: "USC Viterbi · CS",
    image: roommateImages[2],
    match: 94,
    budget: "$1,520/月",
    commute: "USC North / DTLA",
    tags: ["会做饭", "猫友好", "不抽烟", "稳定"]
  },
  {
    id: "seed-roommate-4",
    name: "Leo Wang",
    age: 25,
    role: "Caltech Research Assistant",
    image: roommateImages[3],
    match: 88,
    budget: "$1,480/月",
    commute: "Pasadena / Glendale",
    tags: ["通勤优先", "轻社交", "预算稳定", "长租可谈"]
  },
  {
    id: "seed-roommate-5",
    name: "Sophie Lin",
    age: 21,
    role: "Otis Design · Junior",
    image: roommateImages[4],
    match: 87,
    budget: "$1,720/月",
    commute: "Playa Vista / Culver City",
    tags: ["咖啡党", "不熬夜", "整洁", "接受访客"]
  },
  {
    id: "seed-roommate-6",
    name: "Kevin Zhou",
    age: 26,
    role: "Burbank Studio Intern",
    image: roommateImages[5],
    match: 85,
    budget: "$1,350/月",
    commute: "Burbank / Hollywood",
    tags: ["宠物友好", "做饭频繁", "安静学习", "AA 清楚"]
  },
  {
    id: "seed-roommate-7",
    name: "Grace Xu",
    age: 23,
    role: "UCLA Extension · Film",
    image: roommateImages[6],
    match: 90,
    budget: "$1,780/月",
    commute: "Westwood / Santa Monica",
    tags: ["电影党", "轻社交", "无烟", "带家具优先"]
  },
  {
    id: "seed-roommate-8",
    name: "Ryan Wu",
    age: 24,
    role: "DTLA Finance Analyst",
    image: roommateImages[7],
    match: 86,
    budget: "$1,900/月",
    commute: "DTLA / Arts District",
    tags: ["早起", "健身", "预算稳定", "门卫优先"]
  },
  {
    id: "seed-roommate-9",
    name: "Ivy Huang",
    age: 22,
    role: "USC Marshall · Fall",
    image: roommateImages[8],
    match: 92,
    budget: "$1,560/月",
    commute: "USC / Koreatown",
    tags: ["学习友好", "不抽烟", "爱干净", "偶尔做饭"]
  },
  {
    id: "seed-roommate-10",
    name: "Daniel Kim",
    age: 27,
    role: "Santa Monica SWE",
    image: roommateImages[9],
    match: 89,
    budget: "$2,050/月",
    commute: "Santa Monica / Mar Vista",
    tags: ["安静", "车位优先", "宠物友好", "长期稳定"]
  },
  {
    id: "seed-roommate-11",
    name: "Nora Li",
    age: 25,
    role: "LMU MBA · Evening",
    image: roommateImages[0],
    match: 84,
    budget: "$1,680/月",
    commute: "Playa Vista / Westchester",
    tags: ["晚课", "会做饭", "整洁", "接受访客"]
  },
  {
    id: "seed-roommate-12",
    name: "Jason Yu",
    age: 23,
    role: "Glendale Animation Intern",
    image: roommateImages[1],
    match: 83,
    budget: "$1,420/月",
    commute: "Glendale / Burbank",
    tags: ["影视实习", "猫友好", "安静", "预算友好"]
  },
  {
    id: "seed-roommate-13",
    name: "Emily Zhao",
    age: 22,
    role: "Pasadena ArtCenter",
    image: roommateImages[2],
    match: 88,
    budget: "$1,500/月",
    commute: "Pasadena / Highland Park",
    tags: ["设计学生", "不熬夜", "轻社交", "采光优先"]
  },
  {
    id: "seed-roommate-14",
    name: "Aaron Sun",
    age: 28,
    role: "El Segundo Aerospace PM",
    image: roommateImages[3],
    match: 82,
    budget: "$2,100/月",
    commute: "El Segundo / LAX",
    tags: ["车位优先", "早起", "不抽烟", "整租可谈"]
  },
  {
    id: "seed-roommate-15",
    name: "Claire Guo",
    age: 24,
    role: "Koreatown Healthcare Admin",
    image: roommateImages[4],
    match: 87,
    budget: "$1,380/月",
    commute: "Koreatown / DTLA",
    tags: ["近地铁", "安静", "少做饭", "预算稳定"]
  },
  {
    id: "seed-roommate-16",
    name: "Victor Tan",
    age: 26,
    role: "North Hollywood Editor",
    image: roommateImages[5],
    match: 81,
    budget: "$1,460/月",
    commute: "North Hollywood / Burbank",
    tags: ["影视后期", "夜间安静", "猫友好", "AA 清楚"]
  },
  {
    id: "seed-roommate-17",
    name: "Olivia Park",
    age: 23,
    role: "UCLA Public Health",
    image: roommateImages[6],
    match: 93,
    budget: "$1,740/月",
    commute: "Brentwood / Westwood",
    tags: ["早睡", "健身", "无宠物", "学习友好"]
  },
  {
    id: "seed-roommate-18",
    name: "Mark Chen",
    age: 25,
    role: "Arts District Designer",
    image: roommateImages[7],
    match: 84,
    budget: "$1,880/月",
    commute: "Arts District / Little Tokyo",
    tags: ["咖啡党", "轻社交", "可合租", "门卫优先"]
  },
  {
    id: "seed-roommate-19",
    name: "Selina Ho",
    age: 21,
    role: "USC Annenberg",
    image: roommateImages[8],
    match: 90,
    budget: "$1,590/月",
    commute: "USC / Echo Park",
    tags: ["新闻学生", "不抽烟", "可做饭", "整洁"]
  },
  {
    id: "seed-roommate-20",
    name: "Brian Ma",
    age: 27,
    role: "Silver Lake Startup Ops",
    image: roommateImages[9],
    match: 82,
    budget: "$1,620/月",
    commute: "Silver Lake / Hollywood",
    tags: ["创业公司", "宠物友好", "稳定", "通勤优先"]
  }
];

export const seedGroups = [
  {
    id: "seed-group-1",
    name: "Westside 秋季合租",
    budget: "$6,920/月",
    members: seedRoommates.slice(0, 4)
  },
  {
    id: "seed-group-2",
    name: "USC / Koreatown 通勤组",
    budget: "$4,470/月",
    members: [seedRoommates[2], seedRoommates[8], seedRoommates[14]]
  }
];

export const seedTrips = [
  {
    id: "seed-trip-1",
    listingId: "seed-listing-1",
    title: "Westwood UCLA 步行圈阳光主卧",
    amount: 1680,
    status: "funds_held"
  },
  {
    id: "seed-trip-2",
    listingId: "seed-listing-8",
    title: "USC North 3B2B Group 优选",
    amount: 3620,
    status: "pending_payment"
  }
];

export const seedTrustQueues = [
  { id: "trust-1", label: "人工认证待审", value: 24, variant: "trust" },
  { id: "trust-2", label: "房源媒体审核", value: 11, variant: "warning" },
  { id: "trust-3", label: "退款/缺陷工单", value: 3, variant: "danger" },
  { id: "trust-4", label: "信用分重算队列", value: 128, variant: "success" }
];
